name: deploy
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  id-token: write   # for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TF_INPUT: "false"
      AWS_REGION: us-east-1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::713881788173:role/ssp-github-deploy-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: infra
        run: terraform init -reconfigure

      - name: Terraform Plan
        working-directory: infra
        run: terraform plan -out=plan.out -input=false -lock-timeout=5m -var-file="../terraform.tfvars"

      - name: Terraform Apply
        if: ${{ github.ref == 'refs/heads/main' }}
        working-directory: infra
        run: terraform apply -input=false -auto-approve plan.out

      - name: Sync web (from apps/web) + Invalidate CloudFront
        working-directory: infra
        shell: bash
        run: |
          set -euo pipefail
          WEB_BUCKET=$(terraform output -raw web_bucket)
          DIST_ID=$(terraform output -raw cloudfront_distribution_id)
          aws s3 sync ../apps/web "s3://${WEB_BUCKET}" --delete
          aws cloudfront create-invalidation --distribution-id "$DIST_ID" --paths "/*"

      - name: Show outputs
        working-directory: infra
        run: terraform output
