name: Terraform Deploy

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

concurrency:
  group: portal-terraform
  cancel-in-progress: true

env:
    TF_INPUT: false
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.4
          cli_config_credentials_token: ""  # not needed with OIDC

      # ✅ Configure AWS via OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::713881788173:role/ssp-github-deploy-role
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: infra
        run: terraform init -reconfigure

      - name: Terraform Plan
        working-directory: infra
        run: terraform plan -out=plan.out -var-file="../terraform.tfvars"

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply --auto-approve --var-file="../terraform.tfvars" plan.out

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -input=false -lock-timeout=5m --auto-approve --var-file="../terraform.tfvars" plan.out
        
      - name: Sync web + invalidate CloudFront
        shell: bash
        run: |
          set -euo pipefail
          WEB_BUCKET=$(cd infra && terraform output -raw web_bucket)
          DIST_ID=$(cd infra && terraform output -raw cloudfront_distribution_id)
  
          if [ -d "web" ]; then
          aws s3 sync web "s3://${WEB_BUCKET}" --delete --cache-control "max-age=300"
          fi
          if [ -d "apps/web" ]; then
            aws s3 sync apps/web "s3://${WEB_BUCKET}" --delete --cache-control "max-age=300"
           fi
          aws cloudfront create-invalidation --distribution-id "${DIST_ID}" --paths "/index.html" "/activity.html"
      - name: Show outputs
        working-directory: infra
        run: terraform output
